# Generated by Django 5.0.7 on 2024-08-03 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
