# Generated by Django 5.0.7 on 2024-08-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_interest_timestamp_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='timestamp',
        ),
    ]
