# Generated by Django 5.0.7 on 2024-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_interest_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='sender_notified',
            field=models.BooleanField(default=False),
        ),
    ]
